spring:
   datasource:
     url: jdbc:mysql://localhost:3306/serverdb
     username: root
     password:
     driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
     hibernate:
       ddl-auto: create
       dialect: org.hibernate.dialect.MySQL5Dialect
     properties:
       hibernate:
         dialect:org.hibernate.dialect.MySQL8Dialect
         format_sql:true
        show-sql:true
